In [1]:
import pandas as pd
import requests
import bs4
import re
import json

In [2]:
data = pd.read_csv('new_test_jan.csv')

In [3]:
data.head()

,screen_name,text,favorite_count,retweet_count,date_time,category
0,mrs_pickles,RT @Deborah87164788 INNOCENT. ALLOW RESCUE AND...,0,100,Mon Jan 20 23:59 2020,cage-free
1,hasya_a,"RT @sceneryfortae @BTS_twt relief supplies, dr...",0,144,Mon Jan 20 23:58 2020,cage-free
2,FFTITC,Animal welfare legislation public forums comin...,1,0,Mon Jan 20 23:57 2020,cage-free
3,gerry_truthvet,@MucciTina Free range slave,1,0,Mon Jan 20 23:56 2020,cage-free
4,ukagri,{editor} News story: Expanded Animal Welfare C...,0,0,Mon Jan 20 23:54 2020,cage-free

In [54]:
data['screen_name']

0            mrs_pickles
1                hasya_a
2                 FFTITC
3         gerry_truthvet
4                 ukagri
               ...
118650      livekindlyco
118651             fio_w
118652          Kahreem_
118653     batik_fabrics
118654        mugikikaku
Name: screen_name, Length: 118655, dtype: object

In [69]:
for name in data['screen_name'][:100]:
    print(name)

mrs_pickles
hasya_a
FFTITC
gerry_truthvet
ukagri
AustLiveExports
Kaffe_Takk
audibleakbar
SAFEnewzealand
Christi88873904
DeltaFobz
PhaedraXTeddy
zaddy_key
mankeycat31
EvolvedGuppy
SaftyInNumbers
MEE56674472
laurieket
Carolynmh22
pinkmagnoleah
Raceguy1st
DawnWestcott
judysale23
Paul_R_Canada
openribs
deedou66
MarieCoonan
hmcshiggins
Christian_Pusey
lolabel11
tchevalier10
deedou66
aaaaaaaa6119
Seaturtleisla
PRAEST
Freerange_Inc
Sonntag1M
FactoryFarmCLV
Gertsroyals
guillemrubio
CashCallaghan
Den90490402
fotopak
JerseyInfidel74
Nenagh9
EdwinasAvonBiz
sarahccjohnson
gplnz
hyphybyterhymer
am4huckleberry
GregPappas
aglenergy
UnderYourTree
OasisMountain
cazzatodd
JRTomlinAuthor
Barbi_Twins
suanfha
LewSpears
Robert_Barrone
vivian40883246
Jeggit
NubianVegan
izabellafr
ecocfusco
ghrend
ritahnagaddya
Rustingtongull
ViviSov
pollymniac
howartj
CorinneEnte
grammygrande
KPOPLass94
maraug8288
DrFifiRx
patloupage
serpetinefire99
dmatkins137
CeciliaCmaida
DebbyUoe
thechefsforum
FactoryFarmCLV
julesnewrules
albertarabbit
bobcat0803
robynchercrew
Jools_Orca
AlParsai
CeciliaCmaida
IainMcGill
mary13_g
equikimmy
AnTaisceNW
BillSmith445566
GaynorRogers311
seasylvia2005
mkirby0801
stillwaters1029
mkirby0801

In [2]:
request = requests.get('https://shadowban.eu/mrs_pickles')
request

In [4]:
soup = bs4.BeautifulSoup(request.text, 'html.parser')
soup

<!DOCTYPE doctype html>
<html lang="en"><head><meta charset="utf-8"/><title>Twitter Shadowban Test</title><meta description="Determine wether a Twitter user is shadow banned"/><link href="/favicon/favicon_64.png" rel="icon"/><link href="/favicon/favicon_192.png" rel="apple-touch-icon"/><link crossorigin="use-credentials" href="/manifest.json" rel="manifest"/><meta content="width=device-width,initial-scale=1" name="viewport"><meta content="Twitter, Shadowban, Shadowbanned, Ban, Block, Quality Filter, QFD" name="keywords"/><meta content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1" name="viewport"/><meta content="Twitter Shadowban Test" property="og:title"/><meta content="Are you shadowbanned on Twitter?" property="og:description"/><meta content="/img/sm_preview.png" property="og:image"/><meta content="" property="og:url"/><meta content="Twitter Shadowban Test" property="og:site_name"/><meta content="summary_large_image" name="twitter:card"/><meta content="shadwoban.eu" name="twitter:image:alt"/><meta content="#1481c3" name="theme-color"><link href="/favicon/favicon.svg" rel="prefetch"/><link href="/icons/ban.svg" rel="prefetch"/><link href="/icons/check.svg" rel="prefetch"/><link href="/icons/error.svg" rel="prefetch"/><link href="/icons/gears.svg" rel="prefetch"/><link href="/icons/help.svg" rel="prefetch"/><link href="/icons/help.svg" rel="prefetch"/><link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/><link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet"/><link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet"/><link href="/static/css/main.719d1a6c.chunk.css" rel="stylesheet"/></meta></meta></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(p){function e(e){for(var r,t,n=e[0],o=e[1],u=e[2],a=0,l=[];a<n.length;a++)t=n[a],Object.prototype.hasOwnProperty.call(i,t)&&i[t]&&l.push(i[t][0]),i[t]=0;for(r in o)Object.prototype.hasOwnProperty.call(o,r)&&(p[r]=o[r]);for(s&&s(e);l.length;)l.shift()();return c.push.apply(c,u||[]),f()}function f(){for(var e,r=0;r<c.length;r++){for(var t=c[r],n=!0,o=1;o<t.length;o++){var u=t[o];0!==i[u]&&(n=!1)}n&&(c.splice(r--,1),e=a(a.s=t[0]))}return e}var t={},i={1:0},c=[];function a(e){if(t[e])return t[e].exports;var r=t[e]={i:e,l:!1,exports:{}};return p[e].call(r.exports,r,r.exports,a),r.l=!0,r.exports}a.m=p,a.c=t,a.d=function(e,r,t){a.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},a.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},a.t=function(r,e){if(1&e&&(r=a(r)),8&e)return r;if(4&e&&"object"==typeof r&&r&&r.__esModule)return r;var t=Object.create(null);if(a.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:r}),2&e&&"string"!=typeof r)for(var n in r)a.d(t,n,function(e){return r[e]}.bind(null,n));return t},a.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return a.d(r,"a",r),r},a.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},a.p="/";var r=this["webpackJsonpshadowban-eu-pwa"]=this["webpackJsonpshadowban-eu-pwa"]||[],n=r.push.bind(r);r.push=e,r=r.slice();for(var o=0;o<r.length;o++)e(r[o]);var s=n;f()}([])</script><script src="/static/js/2.dec3b6f6.chunk.js"></script><script src="/static/js/main.685dd1ab.chunk.js"></script></body></html>

In [8]:
print(soup.prettify())

<!DOCTYPE doctype html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <title>
   Twitter Shadowban Test
  </title>
  <meta description="Determine wether a Twitter user is shadow banned"/>
  <link href="/favicon/favicon_64.png" rel="icon"/>
  <link href="/favicon/favicon_192.png" rel="apple-touch-icon"/>
  <link crossorigin="use-credentials" href="/manifest.json" rel="manifest"/>
  <meta content="width=device-width,initial-scale=1" name="viewport">
   <meta content="Twitter, Shadowban, Shadowbanned, Ban, Block, Quality Filter, QFD" name="keywords"/>
   <meta content="width=device-width,initial-scale=1,maximum-scale=1,minimum-scale=1" name="viewport"/>
   <meta content="Twitter Shadowban Test" property="og:title"/>
   <meta content="Are you shadowbanned on Twitter?" property="og:description"/>
   <meta content="/img/sm_preview.png" property="og:image"/>
   <meta content="" property="og:url"/>
   <meta content="Twitter Shadowban Test" property="og:site_name"/>
   <meta content="summary_large_image" name="twitter:card"/>
   <meta content="shadwoban.eu" name="twitter:image:alt"/>
   <meta content="#1481c3" name="theme-color">
    <link href="/favicon/favicon.svg" rel="prefetch"/>
    <link href="/icons/ban.svg" rel="prefetch"/>
    <link href="/icons/check.svg" rel="prefetch"/>
    <link href="/icons/error.svg" rel="prefetch"/>
    <link href="/icons/gears.svg" rel="prefetch"/>
    <link href="/icons/help.svg" rel="prefetch"/>
    <link href="/icons/help.svg" rel="prefetch"/>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet"/>
    <link href="/static/css/main.719d1a6c.chunk.css" rel="stylesheet"/>
   </meta>
  </meta>
 </head>
 <body>
  <noscript>
   You need to enable JavaScript to run this app.
  </noscript>
  <div id="root">
  </div>
  <script>
   !function(p){function e(e){for(var r,t,n=e[0],o=e[1],u=e[2],a=0,l=[];a<n.length;a++)t=n[a],Object.prototype.hasOwnProperty.call(i,t)&&i[t]&&l.push(i[t][0]),i[t]=0;for(r in o)Object.prototype.hasOwnProperty.call(o,r)&&(p[r]=o[r]);for(s&&s(e);l.length;)l.shift()();return c.push.apply(c,u||[]),f()}function f(){for(var e,r=0;r<c.length;r++){for(var t=c[r],n=!0,o=1;o<t.length;o++){var u=t[o];0!==i[u]&&(n=!1)}n&&(c.splice(r--,1),e=a(a.s=t[0]))}return e}var t={},i={1:0},c=[];function a(e){if(t[e])return t[e].exports;var r=t[e]={i:e,l:!1,exports:{}};return p[e].call(r.exports,r,r.exports,a),r.l=!0,r.exports}a.m=p,a.c=t,a.d=function(e,r,t){a.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},a.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},a.t=function(r,e){if(1&e&&(r=a(r)),8&e)return r;if(4&e&&"object"==typeof r&&r&&r.__esModule)return r;var t=Object.create(null);if(a.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:r}),2&e&&"string"!=typeof r)for(var n in r)a.d(t,n,function(e){return r[e]}.bind(null,n));return t},a.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return a.d(r,"a",r),r},a.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},a.p="/";var r=this["webpackJsonpshadowban-eu-pwa"]=this["webpackJsonpshadowban-eu-pwa"]||[],n=r.push.bind(r);r.push=e,r=r.slice();for(var o=0;o<r.length;o++)e(r[o]);var s=n;f()}([])
  </script>
  <script src="/static/js/2.dec3b6f6.chunk.js">
  </script>
  <script src="/static/js/main.685dd1ab.chunk.js">
  </script>
 </body>
</html>

In [12]:
print(soup.get_text())

Twitter Shadowban TestYou need to enable JavaScript to run this app.!function(p){function e(e){for(var r,t,n=e[0],o=e[1],u=e[2],a=0,l=[];a<n.length;a++)t=n[a],Object.prototype.hasOwnProperty.call(i,t)&&i[t]&&l.push(i[t][0]),i[t]=0;for(r in o)Object.prototype.hasOwnProperty.call(o,r)&&(p[r]=o[r]);for(s&&s(e);l.length;)l.shift()();return c.push.apply(c,u||[]),f()}function f(){for(var e,r=0;r<c.length;r++){for(var t=c[r],n=!0,o=1;o<t.length;o++){var u=t[o];0!==i[u]&&(n=!1)}n&&(c.splice(r--,1),e=a(a.s=t[0]))}return e}var t={},i={1:0},c=[];function a(e){if(t[e])return t[e].exports;var r=t[e]={i:e,l:!1,exports:{}};return p[e].call(r.exports,r,r.exports,a),r.l=!0,r.exports}a.m=p,a.c=t,a.d=function(e,r,t){a.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:t})},a.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},a.t=function(r,e){if(1&e&&(r=a(r)),8&e)return r;if(4&e&&"object"==typeof r&&r&&r.__esModule)return r;var t=Object.create(null);if(a.r(t),Object.defineProperty(t,"default",{enumerable:!0,value:r}),2&e&&"string"!=typeof r)for(var n in r)a.d(t,n,function(e){return r[e]}.bind(null,n));return t},a.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return a.d(r,"a",r),r},a.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},a.p="/";var r=this["webpackJsonpshadowban-eu-pwa"]=this["webpackJsonpshadowban-eu-pwa"]||[],n=r.push.bind(r);r.push=e,r=r.slice();for(var o=0;o<r.length;o++)e(r[o]);var s=n;f()}([])

In [4]:
res = requests.get('https://api.shadowban.io/api/v1/twitter/@FFTITC')

In [17]:
res.text

'{"data":{"message":"Check successful.","banned":false}}'

In [10]:
regex = '"message":"(\w+\s?\w+).","banned":(\w+)'

In [49]:
yo = re.search(regex, res.text)

In [51]:
yo.group(1)

'Check successful'

In [11]:
banned = []
check_not_success = []
for screen_name in data['screen_name'][:1000]:
    res = requests.get('https://api.shadowban.io/api/v1/twitter/@{0}'.format(screen_name))
    match = re.search(regex, res.text)
    if match.group(1) != 'Check successful':
        check_not_success.append(screen_name)
    if match.group(2) == 'true':
        banned.append(screen_name)

In [35]:
banned

['pinkmagnoleah',
 'P3AUT',
 'LydiaGi90474661',
 'Shann001Shann',
 'AlinaBGuerra1',
 'govnmtgirl',
 'banbloodsports',
 'Christi37162791',
 'JohnFla04637813',
 'CaffeinatedFurr',
 'popsicle_pimp',
 'Pumpkin_Rot',
 'MonsterPerch',
 'PamHigh2',
 '_KevWhite_',
 'slimpickens2916',
 'TracymOshea',
 'TracymOshea',
 'TracymOshea']

In [7]:
data[data['text'] == 'RT @avonworldwide We’re proud to be the first global beauty company to end animal testing across all our markets. For over 30 years, we’ve worked to end animal testing globally and we will keep fighting for positive change. Who’s with us? https://t.co/cTSwwvp1aZ https://t.co/EOZh2WCQUT']

,screen_name,text,favorite_count,retweet_count,date_time,category
45,EdwinasAvonBiz,RT @avonworldwide We’re proud to be the first ...,0,5,Mon Jan 20 23:41 2020,cage-free
1699,EsmerManri12,RT @avonworldwide We’re proud to be the first ...,0,5,Mon Jan 20 15:35 2020,cage-free
2703,EPAA3Rs,RT @avonworldwide We’re proud to be the first ...,0,5,Mon Jan 20 10:06 2020,cage-free
2782,LippyReps,RT @avonworldwide We’re proud to be the first ...,0,5,Mon Jan 20 09:21 2020,cage-free
3624,EdwinasAvonBiz,RT @avonworldwide We’re proud to be the first ...,0,5,Mon Jan 20 23:41 2020,eaa
5638,EsmerManri12,RT @avonworldwide We’re proud to be the first ...,0,5,Mon Jan 20 15:35 2020,eaa
6672,EPAA3Rs,RT @avonworldwide We’re proud to be the first ...,0,5,Mon Jan 20 10:06 2020,eaa
6758,LippyReps,RT @avonworldwide We’re proud to be the first ...,0,5,Mon Jan 20 09:21 2020,eaa
8782,EdwinasAvonBiz,RT @avonworldwide We’re proud to be the first ...,0,5,Mon Jan 20 23:41 2020,other
38223,EsmerManri12,RT @avonworldwide We’re proud to be the first ...,0,5,Mon Jan 20 15:35 2020,other
53893,EPAA3Rs,RT @avonworldwide We’re proud to be the first ...,0,5,Mon Jan 20 10:06 2020,other
55457,LippyReps,RT @avonworldwide We’re proud to be the first ...,0,5,Mon Jan 20 09:21 2020,other

In [43]:
data[data['screen_name'] == 'Mitusha20']

,screen_name,text,favorite_count,retweet_count,date_time,category
4530,Mitusha20,RT @WillowWind64 By what measure do humans bes...,0,88,Mon Jan 20 20:05 2020,eaa
7079,Mitusha20,RT @themuskansharma Where is the humanity? :'(...,0,106,Mon Jan 20 06:57 2020,eaa
20895,Mitusha20,RT @_AnimalAdvocate Fact: #AnimalTesting delay...,0,170,Mon Jan 20 20:06 2020,other
83401,Mitusha20,RT @WillowWind64 By what measure do humans bes...,0,88,Mon Jan 20 20:05 2020,vegan

In [37]:
data.iloc[10659]['text']

'Powerful Banana Drink For Extreme &amp; Rapid Weight Loss https://t.co/jhnxbGzWI7 https://t.co/rRT9VgseSt'

In [9]:
df_dups = data[data.duplicated(['text'], keep='first')]

In [103]:
data

,screen_name,text,favorite_count,retweet_count,date_time,category
0,mrs_pickles,RT @Deborah87164788 INNOCENT. ALLOW RESCUE AND...,0,100,Mon Jan 20 23:59 2020,cage-free
1,hasya_a,"RT @sceneryfortae @BTS_twt relief supplies, dr...",0,144,Mon Jan 20 23:58 2020,cage-free
2,FFTITC,Animal welfare legislation public forums comin...,1,0,Mon Jan 20 23:57 2020,cage-free
3,gerry_truthvet,@MucciTina Free range slave,1,0,Mon Jan 20 23:56 2020,cage-free
4,ukagri,{editor} News story: Expanded Animal Welfare C...,0,0,Mon Jan 20 23:54 2020,cage-free
...,...,...,...,...,...,...
118650,livekindlyco,The #health benefits of a #meatfree diet have ...,24,10,Mon Jan 20 00:00 2020,vegan
118651,fio_w,@VegSmasher @pizzahutuk I had one last night a...,1,0,Mon Jan 20 00:00 2020,vegan
118652,Kahreem_,22 day vegan challangeeeeee https://t.co/H55Ho...,0,0,Mon Jan 20 00:00 2020,vegan
118653,batik_fabrics,"bag and bowls set 3coconut shell bowl ,none ch...",0,1,Mon Jan 20 00:00 2020,vegan
118654,mugikikaku,RT @CookGlobal Shiitake Mushroom and Cabbage L...,0,25,Mon Jan 20 00:00 2020,vegan

In [123]:
df_dups[df_dups['screen_name'] == 'pinkmagnoleah']

,screen_name,text,favorite_count,retweet_count,date_time,category
19,pinkmagnoleah,RT @Deborah87164788 INNOCENT. ALLOW RESCUE AND...,0,100,Mon Jan 20 23:47 2020,cage-free
3593,pinkmagnoleah,RT @Deborah87164788 INNOCENT. ALLOW RESCUE AND...,0,100,Mon Jan 20 23:47 2020,eaa

In [113]:
df_dups

,screen_name,text,favorite_count,retweet_count,date_time,category
13,mankeycat31,RT @Deborah87164788 INNOCENT. ALLOW RESCUE AND...,0,100,Mon Jan 20 23:49 2020,cage-free
19,pinkmagnoleah,RT @Deborah87164788 INNOCENT. ALLOW RESCUE AND...,0,100,Mon Jan 20 23:47 2020,cage-free
21,DawnWestcott,RT @Freedom4Horses I hate the trope in today's...,0,168,Mon Jan 20 23:47 2020,cage-free
22,judysale23,RT @Deborah87164788 INNOCENT. ALLOW RESCUE AND...,0,100,Mon Jan 20 23:46 2020,cage-free
23,Paul_R_Canada,RT @Freedom4Horses I hate the trope in today's...,0,168,Mon Jan 20 23:46 2020,cage-free
...,...,...,...,...,...,...
118638,Alejandro_vegan,RT @BernieSanders Our democracy and our planet...,0,2326,Mon Jan 20 00:00 2020,vegan
118646,mindbodygreen,Tip no. 3 from the team behind @masteringdib: ...,2,2,Mon Jan 20 00:00 2020,vegan
118647,ejlazar,RT @Laurettamylove Daughter vs. Mother Vegan S...,0,4016,Mon Jan 20 00:00 2020,vegan
118649,chamelion_soul,RT @MaryJoe38642126 Make #Veganuary PERMANENT\...,0,105,Mon Jan 20 00:00 2020,vegan
118654,mugikikaku,RT @CookGlobal Shiitake Mushroom and Cabbage L...,0,25,Mon Jan 20 00:00 2020,vegan

In [10]:
df_no_dups = data.drop_duplicates(subset='text', keep="first", inplace=False)

In [117]:
df_no_dups

,screen_name,text,favorite_count,retweet_count,date_time,category
0,mrs_pickles,RT @Deborah87164788 INNOCENT. ALLOW RESCUE AND...,0,100,Mon Jan 20 23:59 2020,cage-free
1,hasya_a,"RT @sceneryfortae @BTS_twt relief supplies, dr...",0,144,Mon Jan 20 23:58 2020,cage-free
2,FFTITC,Animal welfare legislation public forums comin...,1,0,Mon Jan 20 23:57 2020,cage-free
3,gerry_truthvet,@MucciTina Free range slave,1,0,Mon Jan 20 23:56 2020,cage-free
4,ukagri,{editor} News story: Expanded Animal Welfare C...,0,0,Mon Jan 20 23:54 2020,cage-free
...,...,...,...,...,...,...
118648,CraigWi71497020,@Chuffystuff @lukeobxx Poster for why not to b...,1,0,Mon Jan 20 00:00 2020,vegan
118650,livekindlyco,The #health benefits of a #meatfree diet have ...,24,10,Mon Jan 20 00:00 2020,vegan
118651,fio_w,@VegSmasher @pizzahutuk I had one last night a...,1,0,Mon Jan 20 00:00 2020,vegan
118652,Kahreem_,22 day vegan challangeeeeee https://t.co/H55Ho...,0,0,Mon Jan 20 00:00 2020,vegan
118653,batik_fabrics,"bag and bowls set 3coconut shell bowl ,none ch...",0,1,Mon Jan 20 00:00 2020,vegan

In [126]:
df_no_dups[df_no_dups['screen_name'] == 'EdwinasAvonBiz']

,screen_name,text,favorite_count,retweet_count,date_time,category
45,EdwinasAvonBiz,RT @avonworldwide We’re proud to be the first ...,0,5,Mon Jan 20 23:41 2020,cage-free

In [11]:
df_no_dups[df_no_dups['text'] == 'RT @avonworldwide We’re proud to be the first global beauty company to end animal testing across all our markets. For over 30 years, we’ve worked to end animal testing globally and we will keep fighting for positive change. Who’s with us? https://t.co/cTSwwvp1aZ https://t.co/EOZh2WCQUT']

,screen_name,text,favorite_count,retweet_count,date_time,category
45,EdwinasAvonBiz,RT @avonworldwide We’re proud to be the first ...,0,5,Mon Jan 20 23:41 2020,cage-free

In [ ]:
res = requests.get("https://api.shadowban.io/api/v1/twitter/@LippyReps")

In [62]:
res.text

'<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor="white">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx/1.10.3</center>\r\n</body>\r\n</html>\r\n'

In [44]:
d = json.loads(res.text)

In [45]:
d

{'data': {'message': 'Check successful.', 'banned': False}}

In [55]:
res.json()['data']['banned']

False

In [ ]:
from selenium import webdriver

In [7]:
banned

NameError: name 'banned' is not defined

In [3]:
data_two = pd.read_csv('new_test.csv')

In [20]:
data_merge = pd.merge(data, data_two, how='outer')

In [22]:
data_merge

,screen_name,text,favorite_count,retweet_count,date_time,category
0,mrs_pickles,RT @Deborah87164788 INNOCENT. ALLOW RESCUE AND...,0,100,Mon Jan 20 23:59 2020,cage-free
1,hasya_a,"RT @sceneryfortae @BTS_twt relief supplies, dr...",0,144,Mon Jan 20 23:58 2020,cage-free
2,FFTITC,Animal welfare legislation public forums comin...,1,0,Mon Jan 20 23:57 2020,cage-free
3,gerry_truthvet,@MucciTina Free range slave,1,0,Mon Jan 20 23:56 2020,cage-free
4,ukagri,{editor} News story: Expanded Animal Welfare C...,0,0,Mon Jan 20 23:54 2020,cage-free
...,...,...,...,...,...,...
233720,EdmondHawila,"Cool, casual, all you can eat, vegan and very ...",0,0,Fri Dec 13 00:00 2019,vegan
233721,hk_vegan,RT @maryhui Lunchtime protest today (Dec. 12) ...,0,2965,Fri Dec 13 00:00 2019,vegan
233722,__Sumo___,RT @fayekinley if you really want to be vegan ...,0,14835,Fri Dec 13 00:00 2019,vegan
233723,rjorii,RT @fayekinley if you really want to be vegan ...,0,14835,Fri Dec 13 00:00 2019,vegan
233724,Benecosuk,Gifts for Him 🎄\n\nThe perfect blend of organi...,2,1,Fri Dec 13 00:00 2019,vegan

In [23]:
data_merge.drop_duplicates(['screen_name'], keep=False)

,screen_name,text,favorite_count,retweet_count,date_time,category
3,gerry_truthvet,@MucciTina Free range slave,1,0,Mon Jan 20 23:56 2020,cage-free
8,SAFEnewzealand,You have a chance to make your voice heard by ...,14,12,Mon Jan 20 23:53 2020,cage-free
12,zaddy_key,Welp i guess i have no choice but to move arou...,1,0,Mon Jan 20 23:50 2020,cage-free
20,Raceguy1st,RT @Norm_Farrell If we and our descendents are...,0,4,Mon Jan 20 23:47 2020,cage-free
24,openribs,@tzontickind Hm... whatever provides free rang...,0,0,Mon Jan 20 23:46 2020,cage-free
...,...,...,...,...,...,...
233715,Ambeeeeee_,RT @fayekinley if you really want to be vegan ...,0,14835,Fri Dec 13 00:00 2019,vegan
233716,katrynaku,RT @fayekinley if you really want to be vegan ...,0,14835,Fri Dec 13 00:00 2019,vegan
233720,EdmondHawila,"Cool, casual, all you can eat, vegan and very ...",0,0,Fri Dec 13 00:00 2019,vegan
233722,__Sumo___,RT @fayekinley if you really want to be vegan ...,0,14835,Fri Dec 13 00:00 2019,vegan
233723,rjorii,RT @fayekinley if you really want to be vegan ...,0,14835,Fri Dec 13 00:00 2019,vegan