In [53]:
import pandas as pd
import re

In [3]:
data = pd.read_csv("F:/Users/mmatt_000/Faunalytics/all_data/all_csv/all_data_2019-02-03.csv")

In [26]:
data = data[data['category'] == 'other']

In [27]:
data[data['text'].str.contains('og', regex=False)]

,screen_name,text,favorite_count,retweet_count,date_time,category
10157,zarela75,Coming to you this March 2019! U-jam Fitness¬ÆÔ∏è...,0,0,Sun Feb 03 23:59 2019,other
10174,EastCoastGhoul,@R3licX @Boogie2988 I used to back his weight ...,0,0,Sun Feb 03 23:58 2019,other
10178,fombyf,Hamburger Patties with Creamy Tomato Sauce and...,0,0,Sun Feb 03 23:58 2019,other
10205,mindyshear,Booking Lash Lifts and Brows ü§©\n#lashliftmont...,0,0,Sun Feb 03 23:57 2019,other
10209,Kevincorr6,RT @Boogie2988 30 days of clean eating? I fai...,0,8,Sun Feb 03 23:57 2019,other
...,...,...,...,...,...,...
72659,kitchenelia,RT @_Fit4Lyfe_ If your looking for an easy mea...,0,9,Sun Feb 03 00:00 2019,other
72660,PaskiiTheDon,100% supporting her weight loss program üòî http...,5,2,Sun Feb 03 00:00 2019,other
72669,bgclubpc,"Recently, Plover Center Member Council kids to...",0,0,Sun Feb 03 00:00 2019,other
72671,the_best_daily,20% OFF #sale #save #Yoga #mat #yogamat @amazo...,0,0,Sun Feb 03 00:00 2019,other
72683,FarmZillaClass,ORGANIC PRODUCERS ASSOCIATION of MANITOBA COOP...,0,0,Sun Feb 03 00:00 2019,other

In [32]:
categories = ['animal testing', 'cruelty free', 'humane']
new_data = pd.DataFrame()
for category in categories:
    found_data = data[data['text'].str.contains(category, regex=False)]
    new_data = new_data.append(found_data)

In [33]:
all_data = pd.read_csv("F:/Users/mmatt_000/Faunalytics/all_data/all_csv/all_data_2019-02-03.csv")

In [52]:
data[~data.index.isin(new_data.index)]

,screen_name,text,favorite_count,retweet_count,date_time,category
10143,JosiahDNovak,RT @josiahfitness I never thought I‚Äôd have kid...,0,9,Sun Feb 03 23:59 2019,other
10144,wheresdanith,@sethodell Congrats! Keto is so difficult to s...,1,0,Sun Feb 03 23:59 2019,other
10145,JosiahDNovak,RT @josiahfitness I was once 80 lbs overweight...,0,165,Sun Feb 03 23:59 2019,other
10146,aerofanatic,Making my own keto friendly pizza for the game...,0,0,Sun Feb 03 23:59 2019,other
10147,edsmlls,RT @DanBilzerian I think fat shaming is like m...,0,3826,Sun Feb 03 23:59 2019,other
...,...,...,...,...,...,...
72681,HeartNOLA,Walk for a healthier you! Research has shown t...,0,0,Sun Feb 03 00:00 2019,other
72682,ECHospital,"MOVE Health Tip: Join a walking group, practic...",2,1,Sun Feb 03 00:00 2019,other
72683,FarmZillaClass,ORGANIC PRODUCERS ASSOCIATION of MANITOBA COOP...,0,0,Sun Feb 03 00:00 2019,other
72684,Blonyx,Research: Beta Alanine enhances judo-related p...,0,0,Sun Feb 03 00:00 2019,other
72685,HerbaZest,Making #goldenberry #jam at home is an excelle...,0,0,Sun Feb 03 00:00 2019,other

In [41]:
all_data.loc[10143]

screen_name                                            JosiahDNovak
text              RT @josiahfitness I never thought I‚Äôd have kid...
favorite_count                                                    0
retweet_count                                                     9
date_time                                     Sun Feb 03 23:59 2019
category                                                      other
Name: 10143, dtype: object

In [45]:
data.drop(new_data.index)

,screen_name,text,favorite_count,retweet_count,date_time,category
10143,JosiahDNovak,RT @josiahfitness I never thought I‚Äôd have kid...,0,9,Sun Feb 03 23:59 2019,other
10144,wheresdanith,@sethodell Congrats! Keto is so difficult to s...,1,0,Sun Feb 03 23:59 2019,other
10145,JosiahDNovak,RT @josiahfitness I was once 80 lbs overweight...,0,165,Sun Feb 03 23:59 2019,other
10146,aerofanatic,Making my own keto friendly pizza for the game...,0,0,Sun Feb 03 23:59 2019,other
10147,edsmlls,RT @DanBilzerian I think fat shaming is like m...,0,3826,Sun Feb 03 23:59 2019,other
...,...,...,...,...,...,...
72681,HeartNOLA,Walk for a healthier you! Research has shown t...,0,0,Sun Feb 03 00:00 2019,other
72682,ECHospital,"MOVE Health Tip: Join a walking group, practic...",2,1,Sun Feb 03 00:00 2019,other
72683,FarmZillaClass,ORGANIC PRODUCERS ASSOCIATION of MANITOBA COOP...,0,0,Sun Feb 03 00:00 2019,other
72684,Blonyx,Research: Beta Alanine enhances judo-related p...,0,0,Sun Feb 03 00:00 2019,other
72685,HerbaZest,Making #goldenberry #jam at home is an excelle...,0,0,Sun Feb 03 00:00 2019,other

In [50]:
all_data.drop(data[~data['text'].isin(new_data['text'])].index)

,screen_name,text,favorite_count,retweet_count,date_time,category
0,SammyTherese,@AnimalLeague And 85 likes and 1 comment. No o...,2,0,Sun Feb 03 23:59 2019,cage-free
1,zGCSKd8udxyCO9V,RT @ciwf See the world through their eyes‚Ä¶ \n\...,0,178,Sun Feb 03 23:59 2019,cage-free
2,WhistlingWhist,RT @Jennsworld1 An invite to a party by Emanue...,0,5,Sun Feb 03 23:59 2019,cage-free
3,genya4444,RT @altusda Extremely disturbing story about B...,0,62,Sun Feb 03 23:58 2019,cage-free
4,MeZausted,RT @finnforchange #FinnHour\n\nThe @scotgov ha...,0,41,Sun Feb 03 23:58 2019,cage-free
...,...,...,...,...,...,...
112077,JakeHargisBooks,Vibrant Health - Green Vibrance https://t.co/...,1,0,Sun Feb 03 00:00 2019,vegan
112078,shaylagilkes,RT @dnrhds Things the UK can't deal with:\nTwo...,0,19954,Sun Feb 03 00:00 2019,vegan
112079,capitalreg318,That vegan lifestyle is surely not for me. I'd...,2,0,Sun Feb 03 00:00 2019,vegan
112080,foe_us,Adhering to a plant-based diet is better for t...,11,12,Sun Feb 03 00:00 2019,vegan
112081,we963pdx,Are willing to go vegan for free Beyonce and J...,0,0,Sun Feb 03 00:00 2019,vegan

In [54]:
filename = "F:/Users/mmatt_000/Faunalytics/all_data/all_csv/all_data_2019-02-03.csv"

In [63]:
a = re.findall('all_data_\d+-\d+-\d+\.csv', filename)

In [65]:
a[0]

'all_data_2019-02-03.csv'